import type {Booking, BookingStatus, Rating, Service, Worker, User} from "../types";
import { getAuthToken, clearAuthSession } from "../utils/authStorage";
const API_URL = (import.meta.env.VITE_API_URL || "https://karmiq.onrender.com").replace(/\/+$/, "");
const BASE = API_URL.endsWith("/api") ? API_URL : `${API_URL}/api`;
function normalize(v:any):any{if(Array.isArray(v))return v.map(normalize);if(v&&typeof v==="object"){const out:any={...v};if(out._id&&!out.id)out.id=String(out._id);for(const k of Object.keys(out))out[k]=normalize(out[k]);return out}return v}
async function request<T>(path:string,options:RequestInit={}):Promise<T>{const token=getAuthToken();const res=await fetch(`${BASE}${path}`,{...options,headers:{"Content-Type":"application/json",...(token?{Authorization:`Bearer ${token}`}:{ }),...(options.headers||{})}});let body:any=null;const text=await res.text();try{body=JSON.parse(text)}catch{body={success:false,message:text||res.statusText||"Request failed"}}if(!res.ok||!body.success){if(res.status===401&&path!=="/auth/login"){clearAuthSession();window.dispatchEvent(new Event("karmiq:logout"));window.dispatchEvent(new Event("kaamsaathi:logout"));}throw new Error(body.message||"Request failed");}return normalize(body.data) as T}
export const api={getServices:()=>request<Service[]>("/services"),getService:(id:string)=>request<Service>(`/services/${id}`),getWorkers:()=>request<any[]>("/workers"),getNearbyWorkers:(serviceName:string,lat?:number,lng?:number)=>request<any[]>(`/workers/nearby?service=${encodeURIComponent(serviceName)}${lat?`&lat=${lat}`:""}${lng?`&lng=${lng}`:""}`),getWorker:(id:string)=>request<any>(`/workers/${id}`),
createBooking:(input:any)=>request<Booking>("/bookings",{method:"POST",body:JSON.stringify(input)}),getBookings:()=>request<Booking[]>("/bookings"),getBooking:(id:string)=>request<Booking>(`/bookings/${id}`),updateBookingStatus:(id:string,status:BookingStatus,updates?:any)=>request<Booking>(`/bookings/${id}/status`,{method:"PATCH",body:JSON.stringify({status,...updates})}),cancelBooking:(id:string)=>request<Booking>(`/bookings/${id}/cancel`,{method:"PATCH"}),submitRating:(r:Rating)=>request<Rating>("/reviews",{method:"POST",body:JSON.stringify(r)}),processPayment:(bookingId:string,method:string)=>request<any>("/payments",{method:"POST",body:JSON.stringify({bookingId,method})}),getPayments:()=>request<any[]>("/payments"),getNotifications:()=>request<any[]>("/notifications"),readNotification:(id:string)=>request<any>(`/notifications/${id}/read`,{method:"PATCH"}),readAllNotifications:()=>request<any>("/notifications/read-all",{method:"PATCH"}),deleteNotification:(id:string)=>request<any>(`/notifications/${id}`,{method:"DELETE"}),getWorkerMe:()=>request<any>("/workers/me"),getWorkerJobs:()=>request<any[]>("/worker/jobs"),getActiveWorkerJob:()=>request<any>("/worker/jobs/active"),setWorkerAvailability:(availability:string)=>request<any>("/workers/availability",{method:"PATCH",body:JSON.stringify({availability})}),setWorkerLocation:(lat:number,lng:number)=>request<any>("/workers/location",{method:"PATCH",body:JSON.stringify({lat,lng})}),verifySelf:()=>request<any>("/workers/verify-self",{method:"PATCH"}),getAdminAnalytics:()=>request<any>("/admin/analytics"),getAdminWorkers:()=>request<any[]>("/workers"),getAdminCustomers:()=>request<any[]>("/admin/customers"),getAdminBookings:()=>request<any[]>("/admin/bookings"),getComplaints:()=>request<any[]>("/admin/complaints"),setVerification:(id:string,status:string)=>request<any>(`/admin/workers/${id}/verification`,{method:"PATCH",body:JSON.stringify({status})}),setComplaintStatus:(id:string,status:string)=>request<any>(`/admin/complaints/${id}/status`,{method:"PATCH",body:JSON.stringify({status})}),getMe:()=>request<User>("/auth/me")};
export async function login(phone:string,password:string){return request<{user:User;token:string}>("/auth/login",{method:"POST",body:JSON.stringify({phone,password})})}
export async function register(input:any){return request<{user:User;token:string}>("/auth/register",{method:"POST",body:JSON.stringify(input)})}
export const getServices=api.getServices,getWorkers=api.getWorkers,getNearbyWorkers=api.getNearbyWorkers,getWorker=api.getWorker,createBooking=api.createBooking,getBookings=api.getBookings,getBooking=api.getBooking,updateBookingStatus=api.updateBookingStatus,submitRating=api.submitRating,processPayment=api.processPayment,getAdminAnalytics=api.getAdminAnalytics;
